#!/usr/bin/env ruby
require 'rubygems'
require 'nokogiri'
require 'open-uri'

FPAGE = 'http://finance.yahoo.com/q?s=EURINR=X'
XPATH = '//span[@id="yfs_l10_eurinr=x"]'

amount = (ARGV.length == 1) ? ARGV[0].to_f : 1
amount = 1 if amount == 0

doc = Nokogiri::XML(URI.parse( FPAGE ).read)
element = doc.search( XPATH )
exchange_rate = element[0].children[0].to_s.to_f
puts "#{amount} EUR = #{amount * exchange_rate} INR"
