#!/usr/bin/env ruby
require 'rubygems'
require 'hpricot'
require 'open-uri'

FPAGE = 'http://finance.yahoo.com/q?s=USDINR=X'
XPATH = '/html/body/div/div[2]/div[4]/div[2]/div/div[2]/table/tr/td/big/b/span/'

amount = (ARGV.length == 1) ? ARGV[0].to_f : 1
amount = 1 if amount == 0

doc = Hpricot(URI.parse( FPAGE ).read)
element = doc.search( XPATH )
exchange_rate = element[0].to_s.to_f
puts "#{amount} USD = #{amount * exchange_rate} INR"

